// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtgEeiJ7XTMzChiH0MDZTWqpEBL148hg4',
    appId: '1:194399667304:web:1eff7c5194a78450b627dd',
    messagingSenderId: '194399667304',
    projectId: 'kuro-ec80f',
    authDomain: 'kuro-ec80f.firebaseapp.com',
    databaseURL: 'https://kuro-ec80f-default-rtdb.firebaseio.com',
    storageBucket: 'kuro-ec80f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCltLvYGk75wUihi8Ihx7UfhWSQcTa_QpE',
    appId: '1:194399667304:android:f7b3dc0cb38419a9b627dd',
    messagingSenderId: '194399667304',
    projectId: 'kuro-ec80f',
    databaseURL: 'https://kuro-ec80f-default-rtdb.firebaseio.com',
    storageBucket: 'kuro-ec80f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ZY_vYOUEYkq3zt9c8mGPWUhHBKBDRv8',
    appId: '1:194399667304:ios:4ac0aba8eebaefcbb627dd',
    messagingSenderId: '194399667304',
    projectId: 'kuro-ec80f',
    databaseURL: 'https://kuro-ec80f-default-rtdb.firebaseio.com',
    storageBucket: 'kuro-ec80f.firebasestorage.app',
    iosBundleId: 'com.example.flutterMobileUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8ZY_vYOUEYkq3zt9c8mGPWUhHBKBDRv8',
    appId: '1:194399667304:ios:4ac0aba8eebaefcbb627dd',
    messagingSenderId: '194399667304',
    projectId: 'kuro-ec80f',
    databaseURL: 'https://kuro-ec80f-default-rtdb.firebaseio.com',
    storageBucket: 'kuro-ec80f.firebasestorage.app',
    iosBundleId: 'com.example.flutterMobileUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtgEeiJ7XTMzChiH0MDZTWqpEBL148hg4',
    appId: '1:194399667304:web:3a4cf68003d19f68b627dd',
    messagingSenderId: '194399667304',
    projectId: 'kuro-ec80f',
    authDomain: 'kuro-ec80f.firebaseapp.com',
    databaseURL: 'https://kuro-ec80f-default-rtdb.firebaseio.com',
    storageBucket: 'kuro-ec80f.firebasestorage.app',
  );
}
